### ISSUE TITLE
Einheitliche Benennung der Charaktere, Szenarien

### ISSUE THREAD

**Issue by 1blankz7** [program-and-play/scenarios#12]
Vielleicht isländisch, klingonisch oder ähnliches

**Comment by 1blankz7** [comment]
## Vorschläge
- `Zauberer`: Ythen, Ashal, Svin, Ythens, Nenra, Fenen, Kelyn, Svalen, Syn, Sithin
- `Sidekick`: Iri, Skale, Ashal, Ythast, Chashral, Nenen
- `Silencio`: Ranastilis, Nebukadnezar
- Welten:
  - `1. Welt`: Wadichqo
  - `2. Welt`: ChadIchqo
  - `3. Welt`: WejdIchqo
  - `4. Welt`: Losdichqo
  - `5. Welt`: VaghdIchqo
  - `6. Welt`: AvdIchqo

**Comment by 1blankz7** [comment]
Zauberer: Nenra

Sidekick: Skale

Silencio: Udoq

**Comment by lukas9393** [comment]
Zauberer: Jahrva

Sidekick: Scalen

Silencio: Udoq?

Welt: Bittererde
