### ISSUE TITLE
Kapitel5_notwendige_Funktionalitaeten

### ISSUE THREAD

**Issue by paul2302** [program-and-play/scenarios#23]
Für das Kapitel5A wird benötigt:
-setzeAufSpielfeld(zeile,spalte,object)  (aufgerufen auf dem Spielfeldwrapper
-der Steinbeißer muss laufen und sich drehen können
-der steinbeißer muss einen stein zerbeißen können und er braucht einen counter, da er nicht mehr als x
steine in kap 5 zerbeißen darf

Für das Kapitel5B wird benötigt:
-der steinbeißer soll steine verschieben können, aber immer nur um 1 feld, die methode kriegt dennoch zu lernzwecken 2 positionen (diagonal schieben entspricht 2 feldern, ist also verboten)
-steinVerschieben(zeileStart,spalteStart,zeileZiel,spalteZiel)
-der zauberer soll würfeln können 
-random(minZahl,maxZahl) liefert eine zufallszahl im übergebenen intervall inklusive min und maxzahl

**Comment by lukas9393** [comment]
> -der steinbeißer muss einen stein zerbeißen können und er braucht einen counter, da er nicht mehr als x

Wann wird entschieden was für x steht?

> -der steinbeißer soll steine verschieben können, aber immer nur um 1 feld, die methode kriegt dennoch zu lernzwecken 2 positionen (diagonal schieben entspricht 2 feldern, ist also verboten)

Ich verstehe das nicht ganz. Meinst du es soll eine Methode geben die zwei Indizes übergeben bekommt und wenn diese sich um den Steinbeißer befindet (außer diagonale Kacheln) soll er den Stein um eine Kachel schieben?
`public void steinSchieben(int x, int y)`

Nein, also ich verstehe nicht den Sinn dahinter. Also was ist zeileStart und spalteStart? 
`steinVerschieben(zeileStart,spalteStart,zeileZiel,spalteZiel)`

>

**Comment by paul2302** [comment]
Als X kannst du 3 nehmen.
Lass das verschieben mal weg.  Das sollen die dann selber schreiben
random fällt komplett raus.
