### ISSUE TITLE
Kap. 2 Es sind wieder alle Klasen zu sehen ;-) siehe Screenshot

### ISSUE THREAD

**Issue by schorzz** [program-and-play/scenarios#35]
![bildschirmfoto 2017-01-20 um 17 29 09](https://cloud.githubusercontent.com/assets/1129075/22156822/49787378-df35-11e6-9ff7-05a200250fa0.png)

**Comment by lukas9393** [comment]
![bildschirmfoto 2017-01-30 um 11 38 05](https://cloud.githubusercontent.com/assets/11976901/22420087/ce645158-e6e0-11e6-86e2-0e62f596832d.png)
Sollte nun so aussehen.
