### ISSUE TITLE
Level2Welt wird nicht benutzt

### ISSUE THREAD

**Issue by schorzz** [program-and-play/scenarios#36]
Die Level2Welt wird beim erstellen einer neuen Welt nicht benutz. In Kapitel 2 müssen Leuchtwesen in der Weltklasse erzeugt werden können!

Sehr wichtig! Wird anfang nächster Woche benötigt.

**Comment by lukas9393** [comment]
Die Act-Methode von der Level2Welt wird nicht ausgeführt. Mir ist nicht bekannt warum das so ist und bis nächster Woche werde ich den Fehler wohl nicht finden. Daher habe ich zwei Lösungen anzubieten: 1. Die Act Methode der LeereWelt zu benutzten - das habe ich schon so gepusht oder 2. Eine andere Klasse schreiben die NICHT von der Welt oder LeereWelt erbt und dort wird eine Act ähnliche Methode von der LeereWelt Act-Methode aufgerufen - Nachteil: diese Klasse wird im Anzeigenbaum bei "Other classes" angezeigt.
