### ISSUE TITLE
Methodenumbennung 

### ISSUE THREAD

**Issue by paul2302** [program-and-play/scenarios#39]
in den sichtbaren Klassen müssen alle Methoden in einheitlicher Sprache benannt werden. Wir hatten uns da auf Deutsch geeinigt. 
Das betrifft zum Beispiel die Klasse World bzw. deren Derivate und die Methode getPlayground, da diese von den Anwendern benutzt werden muss.

**Comment by lukas9393** [comment]
Magst du mal den Code durchschauen und die stellen erwähnen wo das noch nicht der fall ist?
