### ISSUE TITLE
Kapitel 5a, Anforderungen technisch und graphisch!

### ISSUE THREAD

**Issue by paul2302** [program-and-play/scenarios#40]
Für Kapitel 5a wird folgendes benötigt:

-eine 5x8 Welt, die eher dunkel ist.

-eine eingangs und Ausgangsgraphik für die höhle (Position in steinformation5a in dropbox/Drehbücher)

-eine Steingrafik für schwach sichtbare flache Steine, die mal beim ausleuchten richtige Steine werden, oder
  flach bleiben, so dass man **drüber laufen** kann.  die Formation dafür ist in der dropbox. **Stein** kennzeichnet dabei echte Steine, also solche, die nach ausleuchten groß und unpassierbar sind.
**fake** kennzeichnet solche, über die man einfach drüber laufen kann (und nach ausleuchten flach bleiben)

-die Logik dafür, dass man bei einem solchen Stein durch Lichtwesen auf genau dem Feld einen echten Stein sieht (oder eben den Fakestein, siehe Formation).

-der Zauberer muss das Amulett tragen und braucht eine getter-Methode (holeAmulettRaus, oder ähnlicher Name - deutsch)

-die Methode des Amuletts, erzeugeSteinbeißer, muss umbenannt werden in rufeSteinbeißer

**Comment by paul2302** [comment]
Der Steinbeißer muss, wenn er gerufen wird neben Nenrah erscheinen.
Also über ihm am besten.

**Comment by lukas9393** [comment]
> -eine eingangs und Ausgangsgraphik für die höhle (Position in steinformation5a in dropbox/Drehbücher)

Was soll das sein? Ich verstehe das nicht. Kannst du mir das genauer erläutern?

> Der Steinbeißer muss, wenn er gerufen wird neben Nenrah erscheinen.
Also über ihm am besten.

Was ist wenn über dem Zauberer kein Platz ist?
