### ISSUE TITLE
nett2know: Position in Leuchtwesen

### ISSUE THREAD

**Issue by schorzz** [program-and-play/scenarios#42]
![bildschirmfoto 2017-02-15 um 16 15 56](https://cloud.githubusercontent.com/assets/1129075/22980317/56c79cc0-f399-11e6-9e73-2f659e919d3c.png)

Der Inspector zeigt das rote Leuchtwesen. Ist int x & int y die Position auf dem Spielfeld? Wenn ja kommt das mit x=3 & y=4 nicht so ganz hin..

**Comment by lukas9393** [comment]
Für Greenfoot ist die Position schon richtig, in den Wert wird noch der Abstand zwischen Greenfootsrand und dem Spielfeldrand also der Offset dazugerechnet. Ich weiß nicht wie das gelöst werden kann.
