### ISSUE TITLE
Level3 - Nach Maven Build lässt sich Level 3 nicht öffen (siehe Grafik)

### ISSUE THREAD

**Issue by nenrah** [program-and-play/scenarios#50]
![grafik](https://cloud.githubusercontent.com/assets/25482401/23895418/e6365772-08a5-11e7-92cb-2fb82dd0a3d4.png)

**Comment by lukas9393** [comment]
Das kann ich nicht nachvollziehen, gibt es eine Ausgabe der Konsole?

**Comment by nenrah** [comment]
Fehler hattest Du mit Fix #48 schon behoben

Am 14.03.2017 um 14:15 schrieb Lukas Hettwer:

**Comment by nenrah** [comment]
den Fehler hast Du mit fix #48 bereits erledigt :-)
