### ISSUE TITLE
Beim Binden der Drehungen an die Cursortasten, sind die Drehungen nicht immer korrekt

### ISSUE THREAD

**Issue by nenrah** [program-and-play/scenarios#73]
Es werden nicht immer 90-Grad Drehungen ausgeführt. Manchmal springt die Grafik bei rechtswendungen von Blickrichtung Osten auf Blickrichtung Westen. Manchmal springt die Grafik korrekt von Blickrichtung Osten auf Blickrichtung Norden.

**Comment by lukas9393** [comment]
das kann ich nicht reproduzieren, besteht diese Problem möglicherweise nur auf einen Windows rechner?
