### ISSUE TITLE
Kap3 - in Geysier laufen

### ISSUE THREAD

**Issue by schorzz** [program-and-play/scenarios#81]
Wenn Jahrva in einen Geysier läuft, soll er verbrennen und zurück an den Anfang teleportiert werden. Wenn ich mich recht erinnere hatte Percy dafür schon eine Animation.

**Comment by lukas9393** [comment]
ist schon implementiert
<img width="605" alt="screen shot 2017-10-03 at 12 44 11" src="https://user-images.githubusercontent.com/11976901/31121487-a4eef2dc-a838-11e7-8536-62fe352848da.png">
